In [2]:
config_file = 'delineation/configs/dislocation_matching_disp_and_warp_and var_home.yml'
aug_config_file = 'delineation/configs/aug.yml'
import torch
from delineation.configs.defaults_segmentation import _C as cfg
from delineation.datasets import make_data_loader
from delineation.models import build_model_list
from delineation.utils import settings, cost_volume_helpers
from delineation.utils.settings import evaluate_results

from tqdm import tqdm
%matplotlib inline
import matplotlib.pyplot as plt
import torch.nn.functional as F

import yaml

cfg.merge_from_file(config_file)
with open(aug_config_file, 'r') as ymlfile:
    cfg_aug = yaml.load(aug_config_file)

_device = settings.initialize_cuda_and_logging(cfg)  # '_device' is GLOBAL VAR

train_loader, val_loader = make_data_loader(cfg, cfg_aug)
seg_model, model = build_model_list(cfg, True)

/home/dagnyt/EPFL/dislocations/delineation/layers/loss.py:6: UserWarning: matplotlib.pyplot as already been imported, this call will have no effect.
  matplotlib.use('agg')
/home/dagnyt/EPFL/dislocations/delineation/utils/settings.py:8: UserWarning: matplotlib.pyplot as already been imported, this call will have no effect.
  matplotlib.use('agg')


Using cuda
unet
=> loaded checkpoint '/home/dagnyt/EPFL/dislocations/models/dislocations_segmentation/150_segmentor.tar' (epoch 150)
=> loaded checkpoint '/home/dagnyt/EPFL/dislocations/models/models_2020_04/dislocations_matching_disp_warp_var_joint_10addaug/150_seg.tar' (epoch 150)
scmnet
=> loaded checkpoint '/home/dagnyt/EPFL/dislocations/models/models_2020_04/dislocations_matching_disp_warp_var_joint_10addaug/150_scmnet_light.tar' (epoch 150)


In [4]:
seg_model.eval()
model.eval()
total_test_loss = 0
pix1_err_m, pix3_err_m, pix5_err_m, epe_m, count = 0, 0, 0, 0, 0
from delineation.utils import settings, cost_volume_helpers

for batch_idx, (l, r, lgt, rgt, dlgt, l_name) in (enumerate(val_loader)):
        indices = cost_volume_helpers.volume_indices(2 * cfg.TRAINING.MAXDISP, len(l),
                                                     cfg.TRAINING.HEIGHT, cfg.TRAINING.WIDTH, _device)

        with torch.no_grad():
            l, r, lgt, rgt, dlgt = l.to(_device), r.to(_device), lgt.to(_device), rgt.to(_device), dlgt.to(_device)

            l_seg, l_segmap = seg_model(l)
            r_seg, r_segmap = seg_model(r)
            if abs(dlgt.max()>32) or abs(dlgt.min()>32):
                continue
                
            print(l_name)
            dl_scores = model(l_segmap, r_segmap)
            
            dl_ = F.softmax(-dl_scores, 2)
            dl = torch.sum(dl_.mul(indices), 2) - cfg.TRAINING.MAXDISP
            for i in range(0, len(dlgt)):
                pix1_err, pix3_err, pix5_err, epe = evaluate_results(dlgt[i], dl[i], lgt[i])
                print(pix1_err, pix3_err, pix5_err, epe, dlgt.min(), dlgt.max())
                pix1_err_m += pix1_err
                pix3_err_m += pix3_err
                pix5_err_m += pix5_err
                epe_m += epe
                count += 1
            torch.cuda.empty_cache()
            
            lgt = lgt.cpu().numpy()
            dl = dl.detach().permute(0, 2, 3, 1).cpu().numpy()
            dlgt = dlgt.unsqueeze(1).detach().permute(0, 2, 3, 1).cpu().numpy()

            for i in tqdm(range(len(dl))):
                vol = cost_volume_helpers.back_project_numpy(lgt[i,0,:,:], dl[i,:,:,:], cfg.TRAINING.MAXDISP, mode='two-sided')
                vol_gt = cost_volume_helpers.back_project_numpy(lgt[i,0,:,:], dlgt[i,:,:,:], cfg.TRAINING.MAXDISP, mode='two-sided')

                for idx, rotation_angle in enumerate(range(-20, 20, 1)):
                    cost_volume_helpers.visualize_volume(l_name[i], vol[0, :, :, :],
                                                         rotation_angle,
                                                         cfg.LOGGING.LOG_DIR,
                                                         mode='scatter',
                                                         save_ext=idx,
                                                         plot=False)

                    cost_volume_helpers.visualize_volume(l_name[i], vol_gt[0, :, :, :],
                                                         rotation_angle,
                                                         cfg.LOGGING.LOG_DIR+'_gt',
                                                         mode='scatter',
                                                         save_ext=idx,
                                                         plot=False)

                torch.cuda.empty_cache()

            
print('here')
values = pix1_err_m / count, pix3_err_m / count, pix5_err_m / count, epe_m / count
print('Mean per dataset: {}, {}, {}, {}'.format(pix1_err_m / count, pix3_err_m / count, pix5_err_m / count, epe_m / count))

('1116_1116 DPC DF4 71.0 kx DF4-B_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.16789667896678967 0.003186850050318685 0.0005031868500503186 0.52003753 tensor(-4., device='cuda:0') tensor(2., device='cuda:0')
[[-1.1124249  -0.9420433  -1.0258274  ... -1.8389931  -1.5169563
  -2.2741013 ]
 [-1.7532749  -1.4341583  -1.5340557  ...  0.9021225  -1.5668869
   0.00769043]
 [-1.3308334  -1.2200966  -1.4194889  ... -0.54496956 -1.3075829
  -1.9120541 ]
 ...
 [-1.0667877  -1.8552666  -1.4779587  ... -1.1177692   0.21821594
  -1.9547386 ]
 [-1.258812   -1.8837719  -1.4870453  ... -0.88077545 -1.1844444
  -0.09703636]
 [-1.22398    -0.52303314 -1.8397274  ...  1.137043    0.5808945
   0.90034866]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-1.1124249  -0.9420433  -1.0258274  ... -1.8389931  -1.5169563
  -2.2741013 ]
 [-1.7532749  -1.4341583  -1.5340557  ...  0.9021225  -1.5668869
   0.00769043]
 [-1.3308334  -1.2200966  -1.4194889  ... -0.54496956 -1.3075829
  -1.9120541 ]
 ...
 [-1.0667877  -1.

100%|██████████| 1/1 [00:36<00:00, 36.97s/it]


('1123_1123 DPC DF4 71.0 kx DF4-B_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.38842700365813104 0.02161622879946791 0.0 0.92714125 tensor(0., device='cuda:0') tensor(7., device='cuda:0')
[[-0.62485313 -0.49292374 -0.55654716 ... -1.4050388  -0.61727715
  -1.022007  ]
 [-1.0612335  -0.7117691  -1.0359402  ...  2.5162277   0.07485199
  -0.3075142 ]
 [-0.73369217 -0.6557007  -0.8281269  ... -0.04685593 -1.2182922
  -0.42568016]
 ...
 [-0.6413441  -1.1866646  -0.6513729  ... -0.89844894  0.42877197
  -1.6571007 ]
 [-0.54162025 -1.1699448  -0.9207878  ... -0.5220642  -1.0408821
  -0.00699043]
 [-0.6783333  -0.07719803 -1.1555882  ...  1.1509438   0.72382355
   0.722126  ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-0.62485313 -0.49292374 -0.55654716 ... -1.4050388  -0.61727715
  -1.022007  ]
 [-1.0612335  -0.7117691  -1.0359402  ...  2.5162277   0.07485199
  -0.3075142 ]
 [-0.73369217 -0.6557007  -0.8281269  ... -0.04685593 -1.2182922
  -0.42568016]
 ...
 [-0.6413441  -1.1866646  -0.651

100%|██████████| 1/1 [00:26<00:00, 26.62s/it]


('2019-12-02_TiAl_box3n15_zoom_1_2_Aligned_9_of_90001_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.40658276863504356 0.0393675379154566 0.002016779606324621 0.9983382 tensor(-4., device='cuda:0') tensor(5., device='cuda:0')
[[-2.413597   -2.8340015  -2.8020725  ...  1.7624931   1.7084503
   0.70240784]
 [-2.7593536  -2.8584213  -3.165823   ...  4.05048     2.4109
   1.8471184 ]
 [-2.3766022  -2.7711582  -2.9838562  ...  2.6981049   1.9728394
   1.7781258 ]
 ...
 [-1.1797638  -1.5140343  -1.2514744  ...  3.7384338   3.328331
   1.1051865 ]
 [-1.1759377  -1.3346329  -1.261591   ...  2.930748    2.0106735
   0.9990654 ]
 [-1.2729607  -0.77910614 -1.4735184  ...  3.364048    3.4436378
   1.5453949 ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-2.413597   -2.8340015  -2.8020725  ...  1.7624931   1.7084503
   0.70240784]
 [-2.7593536  -2.8584213  -3.165823   ...  4.05048     2.4109
   1.8471184 ]
 [-2.3766022  -2.7711582  -2.9838562  ...  2.6981049   1.9728394
   1.7781258 ]
 ...
 [-1.1797638  -1.5140343  -1.

100%|██████████| 1/1 [00:57<00:00, 57.92s/it]


('2019-12-02_TiAl_box3n15_zoom_4_3_Aligned_9_of_90003_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.3970730138308138 0.0470408491476359 0.02146992602122869 1.0705452 tensor(-11., device='cuda:0') tensor(9., device='cuda:0')
[[-2.4583645  -2.8344803  -2.9387207  ...  2.1319199   1.4781761
  -0.32604408]
 [-2.7230911  -2.8928604  -2.9581394  ...  4.526966    2.7188034
   1.5935898 ]
 [-2.3593254  -2.8416252  -3.043188   ...  3.1769295   1.5006714
   0.7572136 ]
 ...
 [ 0.02166748 -0.12749863  0.45461273 ...  0.34901428  0.2349701
  -1.5447273 ]
 [-0.13434029 -0.09826279  0.47567368 ... -1.2443657  -1.5403004
  -0.80960846]
 [-0.16678238 -0.21069336  0.04982376 ...  1.2017365   1.2215195
   1.2117386 ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-2.4583645  -2.8344803  -2.9387207  ...  2.1319199   1.4781761
  -0.32604408]
 [-2.7230911  -2.8928604  -2.9581394  ...  4.526966    2.7188034
   1.5935898 ]
 [-2.3593254  -2.8416252  -3.043188   ...  3.1769295   1.5006714
   0.7572136 ]
 ...
 [ 0.02166748 -0.127498

100%|██████████| 1/1 [00:58<00:00, 58.08s/it]


('2019-12-02_TiAl_box3n15_zoom_7_5_Aligned_9_of_90007_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.4020379805465493 0.08445267870927899 0.031110081828006793 1.189124 tensor(-10., device='cuda:0') tensor(12., device='cuda:0')
[[-2.8255043  -2.9790878  -3.047861   ... -3.114458   -2.2857018
  -2.2119007 ]
 [-3.1797218  -3.1497345  -3.25148    ... -2.3751316  -2.7374134
  -2.0023804 ]
 [-2.859663   -3.0616112  -3.0130043  ... -2.4218826  -2.2884483
  -1.4196281 ]
 ...
 [-2.069418   -1.98242    -2.0404396  ...  2.9897537   3.6762352
   0.60946655]
 [-1.1452618  -2.1852074  -0.9921951  ...  2.0357819   1.5169525
   1.5365677 ]
 [-1.3691769  -2.8990211  -2.1009789  ...  3.2763863   3.5525627
   1.6048927 ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-2.8255043  -2.9790878  -3.047861   ... -3.114458   -2.2857018
  -2.2119007 ]
 [-3.1797218  -3.1497345  -3.25148    ... -2.3751316  -2.7374134
  -2.0023804 ]
 [-2.859663   -3.0616112  -3.0130043  ... -2.4218826  -2.2884483
  -1.4196281 ]
 ...
 [-2.069418   -1.9824

100%|██████████| 1/1 [00:59<00:00, 59.61s/it]


('2019-12-02_TiAl_box3n15_zoom_7_6_Aligned_9_of_90006_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.28430836522689995 0.021791767554479417 0.0 0.80238336 tensor(-6., device='cuda:0') tensor(5., device='cuda:0')
[[-3.7857704  -3.8190098  -4.086712   ... -0.05403137 -0.01836967
  -0.6290226 ]
 [-4.368719   -4.1188965  -4.1003857  ...  0.7198181   0.00702286
  -0.0860672 ]
 [-3.8960266  -4.039665   -4.131939   ...  0.5860443   0.04646301
   0.07420731]
 ...
 [-5.799362   -5.8838234  -5.829626   ...  0.17134857  0.41101456
  -1.1041832 ]
 [-3.427761   -4.44932    -2.2934513  ... -1.3520966  -1.1760292
  -0.8336067 ]
 [-3.3252869  -5.866001   -3.8515816  ...  0.864357    1.2973404
   0.6918335 ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-3.7857704  -3.8190098  -4.086712   ... -0.05403137 -0.01836967
  -0.6290226 ]
 [-4.368719   -4.1188965  -4.1003857  ...  0.7198181   0.00702286
  -0.0860672 ]
 [-3.8960266  -4.039665   -4.131939   ...  0.5860443   0.04646301
   0.07420731]
 ...
 [-5.799362   -5.8838234  -5.

100%|██████████| 1/1 [00:58<00:00, 58.93s/it]


('2507 5 2BC5 ZA3 mag OA20_2507 5 2BC5 ZA3 mag OA20-2_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.29810984605962754 0.01622915680761629 0.00041755978064192856 0.8025016 tensor(-1., device='cuda:0') tensor(4., device='cuda:0')
[[ 0.39677048  0.3416748   0.07415009 ...  0.16921234 -0.11860085
  -1.0405293 ]
 [ 0.30268478  0.21582031 -0.3164444  ...  2.4433365   0.80950546
   0.02431488]
 [ 0.24206924  0.11701584  0.04976273 ...  1.2666397   0.35266495
   0.20586395]
 ...
 [-0.9005432  -1.2445621  -0.8466053  ...  1.1824722   1.3818016
  -0.34384918]
 [-0.76875114 -1.1848488  -1.0420303  ...  0.2644539   0.6311455
   0.4505806 ]
 [-0.70345306 -0.16039848 -0.97732925 ...  2.479084    2.1860123
   2.3009338 ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[ 0.39677048  0.3416748   0.07415009 ...  0.16921234 -0.11860085
  -1.0405293 ]
 [ 0.30268478  0.21582031 -0.3164444  ...  2.4433365   0.80950546
   0.02431488]
 [ 0.24206924  0.11701584  0.04976273 ...  1.2666397   0.35266495
   0.20586395]
 ...
 [-0.9005432 

100%|██████████| 1/1 [02:17<00:00, 137.92s/it]


('TiAl_box3n15_pairs_0_16_img_16_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.7639357114856918 0.5237161897295178 0.4742453939631517 12.504439 tensor(-51., device='cuda:0') tensor(25., device='cuda:0')
[[-4.821125   -5.541443   -5.194126   ... -2.3515663  -0.11190033
  -1.5259781 ]
 [-6.458708   -7.5294876  -5.4162636  ...  8.744434   -0.31916428
   1.5182648 ]
 [-6.404436   -6.7579956  -5.234247   ...  2.181469   -1.9036999
  -0.421772  ]
 ...
 [-0.8383064  -1.4284744  -0.8049011  ...  2.7442017   2.9037933
  -0.11383057]
 [-0.94659615 -1.2362957  -0.8922405  ...  1.6620293   1.6883125
   1.3397903 ]
 [-0.72608376 -1.021143   -1.424406   ...  1.3516693   2.3754272
   0.6457443 ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-4.821125   -5.541443   -5.194126   ... -2.3515663  -0.11190033
  -1.5259781 ]
 [-6.458708   -7.5294876  -5.4162636  ...  8.744434   -0.31916428
   1.5182648 ]
 [-6.404436   -6.7579956  -5.234247   ...  2.181469   -1.9036999
  -0.421772  ]
 ...
 [-0.8383064  -1.42

100%|██████████| 1/1 [00:57<00:00, 57.47s/it]


('TiAl_box3n15_pairs_0_2_img_2_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.5926176514809803 0.17967222973988875 0.05675838219816569 1.7523446 tensor(-10., device='cuda:0') tensor(5., device='cuda:0')
[[-2.9779167  -3.1934948  -3.3830605  ... -2.5963364  -2.5431995
  -2.6770058 ]
 [-3.428978   -3.5194035  -3.8227558  ... -1.7487278  -2.019989
  -2.432928  ]
 [-3.276348   -3.4161625  -3.1824932  ... -2.0864887  -2.6917152
  -1.9292755 ]
 ...
 [-1.2405949  -1.7425785  -1.5756721  ...  3.6473427   3.4618568
   0.61989594]
 [-1.3740196  -1.5640469  -1.4214897  ...  2.3687248   2.3344955
   1.8018951 ]
 [-1.239912   -1.3323555  -1.8929996  ...  2.210041    3.0228348
   0.988945  ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-2.9779167  -3.1934948  -3.3830605  ... -2.5963364  -2.5431995
  -2.6770058 ]
 [-3.428978   -3.5194035  -3.8227558  ... -1.7487278  -2.019989
  -2.432928  ]
 [-3.276348   -3.4161625  -3.1824932  ... -2.0864887  -2.6917152
  -1.9292755 ]
 ...
 [-1.2405949  -1.7425785

100%|██████████| 1/1 [01:01<00:00, 61.52s/it]


('TiAl_box3n15_pairs_0_4_img_4_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.47008162959634536 0.15210065153898 0.0971317306972216 1.7132857 tensor(-13., device='cuda:0') tensor(8., device='cuda:0')
[[-2.7768211  -2.9786491  -3.3355446  ... -4.5093937  -2.7578297
  -3.0368977 ]
 [-3.224945   -3.214531   -3.6061363  ... -1.577282   -2.395153
  -2.5708656 ]
 [-3.0610542  -3.2428474  -3.0289001  ... -3.8701572  -4.2766285
  -2.5074768 ]
 ...
 [-1.0096569  -1.5046501  -1.0572395  ...  4.919586    4.5000114
   1.0094223 ]
 [-1.0783443  -1.2528286  -1.0414677  ...  3.0568008   2.8860588
   2.1580658 ]
 [-0.9396877  -0.98810196 -1.4585953  ...  2.9403992   3.5289116
   1.0653915 ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-2.7768211  -2.9786491  -3.3355446  ... -4.5093937  -2.7578297
  -3.0368977 ]
 [-3.224945   -3.214531   -3.6061363  ... -1.577282   -2.395153
  -2.5708656 ]
 [-3.0610542  -3.2428474  -3.0289001  ... -3.8701572  -4.2766285
  -2.5074768 ]
 ...
 [-1.0096569  -1.5046501  -

100%|██████████| 1/1 [01:00<00:00, 60.81s/it]


('TiAl_box3n15_pairs_0_7_img_7_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.6572186434255399 0.2616142478211444 0.16794240242516104 2.7975967 tensor(-22., device='cuda:0') tensor(11., device='cuda:0')
[[-2.4355793  -2.575098   -2.6226711  ...  0.9647331   1.2220306
  -0.1863823 ]
 [-2.7904434  -2.8722935  -2.890276   ...  6.8485565   3.1423416
   2.5137367 ]
 [-2.6827736  -2.837494   -2.352684   ...  3.4904022   0.7274399
   0.9183655 ]
 ...
 [-1.126751   -1.9125214  -1.6464615  ...  3.125824    3.1890144
   0.15518188]
 [-1.2745934  -1.6455059  -1.4448528  ...  1.8382378   1.8037796
   1.3894577 ]
 [-1.0846748  -1.5615768  -2.0813866  ...  1.3610535   2.406021
   0.6360016 ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-2.4355793  -2.575098   -2.6226711  ...  0.9647331   1.2220306
  -0.1863823 ]
 [-2.7904434  -2.8722935  -2.890276   ...  6.8485565   3.1423416
   2.5137367 ]
 [-2.6827736  -2.837494   -2.352684   ...  3.4904022   0.7274399
   0.9183655 ]
 ...
 [-1.126751   -1.912521

100%|██████████| 1/1 [01:01<00:00, 61.83s/it]


('TiAl_box3n15_pairs_n2_2_img_2_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.7258307021500526 0.344985716433619 0.21124642910840474 3.4957013 tensor(-17., device='cuda:0') tensor(15., device='cuda:0')
[[-0.7009506  -0.86956215 -1.06497    ... -2.2151527  -2.3004704
  -2.7906017 ]
 [-0.9876251  -1.0620003  -1.3915539  ... -0.5934334  -1.5263214
  -1.9451542 ]
 [-1.015131   -1.4256573  -1.1514874  ... -0.90694237 -2.2382164
  -2.054123  ]
 ...
 [-0.642746   -1.0854225  -0.5234451  ...  3.4282684   3.1741447
   0.06930542]
 [-0.6877136  -0.9307537  -0.452116   ...  1.8890152   1.7185745
   1.3339958 ]
 [-0.55265236 -0.56679344 -0.8776283  ...  1.8711472   2.534027
   0.8605614 ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-0.7009506  -0.86956215 -1.06497    ... -2.2151527  -2.3004704
  -2.7906017 ]
 [-0.9876251  -1.0620003  -1.3915539  ... -0.5934334  -1.5263214
  -1.9451542 ]
 [-1.015131   -1.4256573  -1.1514874  ... -0.90694237 -2.2382164
  -2.054123  ]
 ...
 [-0.642746   -1.0854225

100%|██████████| 1/1 [01:01<00:00, 61.65s/it]


('TiAl_box3n15_pairs_n4_4_img_4_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.5682618138246087 0.25087995207069574 0.1524002096907062 2.9390311 tensor(-10., device='cuda:0') tensor(17., device='cuda:0')
[[-1.3482208  -1.3324795  -1.3998394  ... -4.7911797  -2.6742954
  -2.9353924 ]
 [-1.6065998  -1.5328922  -1.6696053  ... -1.5157185  -2.516449
  -2.0377274 ]
 [-1.607027   -1.6868916  -1.3042927  ... -3.278593   -3.537634
  -1.8936157 ]
 ...
 [-0.5931072  -1.129219   -0.49451828 ...  4.511017    4.4371147
   1.1478348 ]
 [-0.66683006 -0.8961811  -0.476614   ...  3.0555954   3.1581116
   2.4662895 ]
 [-0.42204285 -0.5483513  -0.82312584 ...  2.9639816   3.5750847
   1.2421188 ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-1.3482208  -1.3324795  -1.3998394  ... -4.7911797  -2.6742954
  -2.9353924 ]
 [-1.6065998  -1.5328922  -1.6696053  ... -1.5157185  -2.516449
  -2.0377274 ]
 [-1.607027   -1.6868916  -1.3042927  ... -3.278593   -3.537634
  -1.8936157 ]
 ...
 [-0.5931072  -1.129219   

100%|██████████| 1/1 [01:02<00:00, 62.59s/it]


('ant2_ant2-B_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.319942352729238 0.016753738065213474 0.01098901098901099 0.87434644 tensor(-2., device='cuda:0') tensor(7., device='cuda:0')
[[-1.2097759  -1.2408028  -1.2204208  ... -1.334734   -1.341095
  -2.3442879 ]
 [-1.0788288  -1.4133701  -1.3641758  ...  1.8726006  -1.1266308
  -0.67173195]
 [-0.991869   -1.2034683  -1.3416996  ...  0.13005447 -1.8716774
  -1.6146088 ]
 ...
 [-0.8321762  -0.91362    -0.10788918 ...  3.8884888   4.0314827
   2.5315819 ]
 [-0.60396194 -1.0980873  -0.21530533 ...  2.9793777   2.5049667
   1.573288  ]
 [-0.72122955 -0.46009064 -0.6948681  ...  4.2543488   4.1987
   2.474678  ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-1.2097759  -1.2408028  -1.2204208  ... -1.334734   -1.341095
  -2.3442879 ]
 [-1.0788288  -1.4133701  -1.3641758  ...  1.8726006  -1.1266308
  -0.67173195]
 [-0.991869   -1.2034683  -1.3416996  ...  0.13005447 -1.8716774
  -1.6146088 ]
 ...
 [-0.8321762  -0.91362    -

100%|██████████| 1/1 [00:34<00:00, 34.41s/it]


('ant_ant-B_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.2793170674071011 0.022449341289064808 0.002658474626336622 0.81741226 tensor(-3., device='cuda:0') tensor(5., device='cuda:0')
[[-1.888876   -1.8426285  -2.0090752  ...  0.40346146  0.5714531
  -0.28564453]
 [-2.2526436  -2.563877   -2.2029114  ...  1.8042717   0.9536171
   0.80965805]
 [-1.9650364  -2.03434    -2.2978477  ...  1.2091255   0.29944992
   0.28615952]
 ...
 [-0.9451637  -0.9709854  -0.29061127 ...  3.4552383   3.9300385
   2.0262604 ]
 [-1.1177654  -1.1767406  -0.6126213  ...  3.0995522   2.4465942
   1.7920303 ]
 [-0.9147949  -0.83382034 -0.60320663 ...  4.151989    3.826271
   2.252617  ]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[-1.888876   -1.8426285  -2.0090752  ...  0.40346146  0.5714531
  -0.28564453]
 [-2.2526436  -2.563877   -2.2029114  ...  1.8042717   0.9536171
   0.80965805]
 [-1.9650364  -2.03434    -2.2978477  ...  1.2091255   0.29944992
   0.28615952]
 ...
 [-0.9451637  -0.97

100%|██████████| 1/1 [01:12<00:00, 72.45s/it]


('pairs_18_20_GaN - TiltAxis is almost vertical_0018_LEFT.png',)


  0%|          | 0/1 [00:00<?, ?it/s]

0.07107742728390004 0.004916018025399427 0.00040966816878328555 0.49684608 tensor(-1., device='cuda:0') tensor(4., device='cuda:0')
[[ 0.76488113  0.36078262  0.07135773 ... -0.7664108  -0.60871506
  -1.698431  ]
 [ 0.5832596   0.63752747 -0.01145935 ...  4.427265    0.25294876
   0.42229462]
 [ 0.7178383   0.4440956   0.21625519 ...  1.4960823  -1.328949
  -0.70261955]
 ...
 [-1.5591164  -2.2200794  -1.97686    ...  2.3498688   4.2507706
   0.16420746]
 [-1.8200912  -2.214323   -1.947525   ...  1.5847816   0.94887924
   0.7436447 ]
 [-1.6532173  -1.7428322  -2.3545628  ...  2.4215164   3.0461197
   0.43989563]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
[[ 0.76488113  0.36078262  0.07135773 ... -0.7664108  -0.60871506
  -1.698431  ]
 [ 0.5832596   0.63752747 -0.01145935 ...  4.427265    0.25294876
   0.42229462]
 [ 0.7178383   0.4440956   0.21625519 ...  1.4960823  -1.328949
  -0.70261955]
 ...
 [-1.5591164  

100%|██████████| 1/1 [00:49<00:00, 49.91s/it]

here
Mean per dataset: 0.424544916019207, 0.12442332210611107, 0.07683120224707464, 2.1063171699643135
